config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root    'static_pages#home'
  get     '/contact',     to: 'static_pages#contact'
  get     '/signup',      to: 'users#new'
  get     '/login',       to: 'sessions#new'
  post    '/login',       to: 'sessions#create'
  delete  '/logout',      to: 'sessions#destroy'
  get     '/browse',      to: 'items#index'
  get     '/addItem',     to: 'items#new'
  post    '/addItem',     to: 'items#create'
  
  resources :users
  resources :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :item_type
  
  has_attached_file :image, styles: {medium: "300x300>", thumb: "50x50>" }, default_url: "/images/:items/missing.png"
  
  before_save { self.name = name.capitalize }
  validates :name,          presence: true, length: {maximum: 50},  uniqueness: {case_sensitive: false}
  validates :description,   presence: true, length: {maximum: 255}
  validates :item_type_id,  presence: true
  validates :image,         presence: true
  validates_attachment_content_type :image,   content_type: /\Aimage\/.*\z/, presence: true
  
  def self.search(search)
    #where("items.name LIKE ? OR items.description LIKE ?", "%#{search}%", "%#{search}%")
    if search
      joins("JOIN item_types ON items.item_type_id = item_types.id")
        .where("items.name LIKE ? OR items.description LIKE ? OR item_types.description LIKE ? ", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      scoped
    end
  end
  
end

app/models/item_type.rb
class ItemType < ApplicationRecord
  has_many :items
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :logged_in_user,  only: [:new, :edit, :update, :destroy]
  before_action :admin_user,      only: [:new, :edit, :update, :destroy]
  
  helper_method :sort_column, :sort_direction
  
  def show
    @item = Item.find(params[:id])
    @itemType = ItemType.find_by(id: @item.item_type_id)
  end
  
  def index
    @itemTypes = ItemType.all
    if params[:search]
      @items = Item.search(params[:search])
                      .order(sort_column + " " + sort_direction)
                      .paginate(page: params[:page])
    else
      @items = Item.order(sort_column + " " + sort_direction)
                      .paginate(page: params[:page])
    end
    
  end
  
  def new
    @item = Item.new
    #@allItems = Item.all.order(:name)
    #@allItemTypes = ItemType.all
    #@allItems = Item.where("type_id = ?", ItemType.first.id)
  end
  
  def create
    #@item = Item.new(item_params)
    @itemType = ItemType.find_by(id: item_params[:item_type_id])
    # @item = @itemType.items.create(item_params)
    @item = @itemType.items.create(name: item_params[:name], description: item_params[:description], 
                                    image: item_params[:image], item_type_id: item_params[:item_type_id])
    
    if @item.save
      # Handle a successful save.
      flash[:success] = "Item successfully added!"
      redirect_to browse_path
    else
      render 'new'
    end
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      # Handle a successful update
      flash[:success] = "Item updated"
      redirect_to @item
    else
      render 'edit'
    end
  end
  
  def destroy
    Item.find(params[:id]).destroy
    flash[:success] = "Item deleted"
    redirect_to items_url
  end
  
  
  private
  
    # item parameters
    def item_params
      params.require(:item).permit(:name, :description, :item_type_id, :image)
    end
  
    # type parameters
    # def type_params
    #   params.require(:type).permit(:type_id)
    # end
  
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
      store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
  
    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
    # Sorting index columns
    def sort_column
      Item.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_item.html.erb
<tr>
  <td><%= image_tag item.image.url(:thumb) %></td>
  <td><%= link_to item.name, item %></td>
  <td><%= item.description %></td>
  <td><%= item.item_type.description %></td>
</tr>
  

app/views/items/edit.html.erb
<% provide(:title, "Edit item") %>
<h1>Update the selected item</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@item) do |f| %>
      <%= render 'shared/error_messages_item' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/items/index.html.erb
<% provide(:title, 'All items') %>

<h1>All items</h1>

<div>
  <p>
    Optional search tags: <i>Raw Crafting Material</i>, <i>Prime Part</i>, <i>Warframe Primary Weapon</i>
  </p>
  <%= form_tag(items_path, method: "get", id: "search-form") do %>
    <%= label_tag(:search, "Search for:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>

<div>
  <div class="item-slot-filter">
    <ul>
      <li>Item slot > </li>
      <% @itemTypes.each do |type| %>
        <li><a href="#"><%= type.description %></a></li>
      <% end %>
    </ul>
  </div>
  
  <div class="item-source-filter">
    <ul>
      <li> < Crafting source</li>
      <% @itemTypes.each do |type| %>
        <li><a href="#"><%= type.description %></a></li>
      <% end %>
    </ul>
  </div>
</div>

<%= will_paginate %>


<table class="item-table pretty">
  
  <tr>
    <th>Img</th>
    <th><%= sortable "name" %></th>
    <th><%= sortable "description" %></th>
    <th><%= sortable "type_id", "Item Type" %></th>
  </tr>
  
  <% @items.each do |item| %>
    <%= render item %>
  <% end %>
  
</table>

<%= will_paginate %>

<script>

</script>

app/views/items/new.html.erb
<% provide(:title, 'Add item') %>
<h1>Add new item</h1>

<div>
  Guidelines:
  <ul>
    <li>Name, description, image and item type attributes are mandatory</li>
    <li>If an item is constructed out of 2 identical weapons, use 2 separate component selectors with quantity:1 instead of one with quantity:2</li>
    <li>Leave all component selectors blank when adding raw materials to the database</li>
    <li>Images will NOT be scaled to 200x200px size before upload so make sure you upload small images</li>
  </ul>
</div>

<%= form_for @item, :html => {:multipart => true, :class => "add-item-form"} do |f| %>
  <%= render 'shared/error_messages_item' %>

  <div class="new_left">
    <%= f.label :name, "Name:" %>
    <%= f.text_field :name, class: 'form-control' %> 

    <%= f.label :description, "Description:" %>
    <%= f.text_area :description, class: 'form-control' %>
    <br/>
    
    <%= f.label :item_type_id, "Item type:" %>
    <%= f.collection_select :item_type_id, ItemType.all.order(:name), :id, :description, :include_blank => true %>
    
  </div>
  
  <div class="new_right">
    <%= f.label :image, "Select image:" %>
    <%= f.file_field :image %>
    <div id="target"></div>
  </div>
  
  <div class="clear_float">
    <h3>Crafting components:</h3>
  </div>
  


  <div class="clear_float"></div>

  <%= f.submit "Add item", class: "btn btn-primary" %>
<% end %>



<script>
  $(function(){
    $('#item_image').on('change', function(event) {
      var files = event.target.files;
      var image = files[0]
      // here's the file size
      console.log(image.size);
      var reader = new FileReader();
      reader.onload = function(file) {
        var img = new Image();
        console.log(file);
        img.src = file.target.result;
        
        // resize image
        var MAX_WIDTH = 200;
        var MAX_HEIGHT = 200;
        var width = img.width;
        var height = img.height;
         
        if (width > height) {
          if (width > MAX_WIDTH) {
            height *= MAX_WIDTH / width;
            width = MAX_WIDTH;
          }
        } else {
          if (height > MAX_HEIGHT) {
            width *= MAX_HEIGHT / height;
            height = MAX_HEIGHT;
          }
        }
        img.width = width;
        img.height = height;
        
        $('#target').html(img);
      }
      reader.readAsDataURL(image);
      console.log(files);
    });
  });
</script>

app/views/items/show.html.erb
<% provide(:title, @item.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      
      <h1>
        <%= @item.name %>
      </h1>
      
      <p>
         <%= @item.description %>
      </p>
      
      <p>
        Item type: <%= @itemType.description %>
      </p>
      
      <p>
        Image: <br/>
        <%= image_tag @item.image.url %>
        <%= image_tag @item.image.url(:medium) %>
        <%= image_tag @item.image.url(:thumb) %>
      </p>
      
      <p>
        <h3>Admin options:</h3>
        <%= link_to "Edit item", edit_item_path(@item) %>
        <% if current_user.admin? %>
          | 
          <%= link_to "Delete item", @item, method: :delete,
                                        data: { confirm: "You sure?" } %>
        <% end %>
      </p>
      
    </section>
  </aside>
</div>